api:
  endpoint: "http://localhost:7860/"

excel:
  path: "../模板(6).xlsx"    # 输入Excel路径
  sheet: "voiceclone"     # 结果写入的工作表名

paths:
  input_root: "inputs/"     # 输入根目录
  output_root: "F://workspace//python//outputs"     # 输出根目录
  date_format: "%Y-%m-%d"     # 日期路径格式
  log: "logs/"     # 日期路径格式

logging:
  level: "INFO"
  max_bytes: 10485760         # 10MB
  backup_count: 5

# 生成参数
generation:
  text_lang: "中文"
  prompt_lang: "中文"
  speed_factor: 1
  top_k: 5
  sample_steps: 64
  seed: 972782474
  keep_random: False
  voice_name: "使用参考音频"  # 新增音色选择配置
  speed: 1               # 替换原有的speed_factor