# config.yaml
api:
  endpoint: "http://127.0.0.1:7860/"
  name: "/do_make"
  defaults:
    min_resolution: 720
    if_res: False

excel:
  path: "../voiceclone.xlsx"
  sheet: "voiceclone"
  columns:
    video: "数字人"
    audio: "输出音频"
    people: "负责人"

input:
  dir: "F://workspace//python//batch_product//batch_video_product//inputs"

output:
  dir: "G://ai素材//数字人//"
  log_dir: "./outputs/logs"

