# 路径配置
workflow_path: "workflow.json"  # ComfyUI工作流模板路径
#filename_prefix: "output"       # 输出根目录
excel_file: "data.xlsx"         # 数据文件路径

# 模型配置
checkpoint: "flux1-dev-fp8.safetensors"  # 主模型
seed_range: [1, 18446744073709551614]    # 随机种子范围

# 图像参数
width: 728                 # 图像宽度
height: 1024               # 图像高度
batch_size: 4              # 每批数量
max_filename_length: 30    # 文件名最大长度

# 网络设置
max_retries: 3             # 最大重试次数
request_timeout: 30        # 请求超时时间(秒)